FROM ubuntu:24.04

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    docker.io \
    nodejs \
    python3-venv \
    python3-dev && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

ENV THREAD=1 \
    CPU=1 \
    PATH="/app/venv/bin:$PATH"

WORKDIR /app
#RUN git clone https://git.rwth-aachen.de/linsherpa/ms_converter.git /app

#COPY File014.RAW /app
#WORKDIR /app
#RUN chmod 777 -R /tmp
COPY requirements.txt /app
RUN python3 -m venv /app/venv && \
    /app/venv/bin/pip install --no-cache-dir -r requirements.txt

COPY . /app
RUN chmod +x /app/start.sh

EXPOSE 5000
ENTRYPOINT ["/app/start.sh"]
CMD ["sh", "-c", "uwsgi --http-socket :5000 --master --processes ${CPU} --threads ${THREAD} -w rest_api:app"]